name: Trello PR card
on:
  pull_request
    types:
      - opened

jobs:
  create-card:
    uses: dfe-analytical-services/dfeshiny/.github/workflows/create_trello_card_template.yaml@new-feature/trello-pr-workflow
