name: Trello PR card
on:
  pull_request_target:
    types:
      - opened

jobs:
  create-card:
    uses: dfe-analytical-services/dfeshiny/.github/workflows/create_trello_card_template.yaml@main
    secrets:
      TRELLO_API_KEY: '${{ secrets.TRELLO_API_KEY }}'
      TRELLO_API_TOKEN: '${{ secrets.TRELLO_API_TOKEN }}'
