name: Trello PR card
on:
  pull_request_target:
    types:
      - opened

jobs:
  create-card:
    runs-on: ubuntu-latest
    steps:
      - name: create a card
        uses: nentgroup/pr-trello-action@v2
        with:
          api-key: '${{ secrets.TRELLO_API_KEY }}'
          api-token: '${{ secrets.TRELLO_API_TOKEN }}'
          list-id: '63ce5064a4859b0387f46b9b'
          title-format: 'shiny-template PR: ${title}'
          label-ids: |
             63ce4ffcbfa825468a8e2a69
             67b364c6c93cf6560ce8bfdc
